import { useLocation } from "react-router-dom"

const ItemsGroupCard = () => {
  const location = useLocation();

  if(location.pathname !== '/') {
    return null
  }

  return (
    <div className="card flex flex-col justify-around bg-gray-200">
      <h1 class="font-bold text-2xl md:text-4xl">Completed Builds</h1>
      <span class="block text-gray-500 text-sm md:text-lg">Browse thousands of PC builds generated by users showing their partlist, photos and overall build experience.</span>
      <button class="primary-button">View Complete Builds</button>
    </div>
  )
}

export default ItemsGroupCard